### ISSUE TITLE
garden-test-SFCGAL segfaults

### ISSUE THREAD

**Issue by kashif** [Oslandia/SFCGAL#74]
The `garden-test-SFCGAL` test segfaults on OSX 10.10 with:

```
$ clang -v                                                   
Apple LLVM version 6.1.0 (clang-602.0.48) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
```

compiled with cgal 4.5.2. The backtrace is:

```
Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x0000000000000028
0x00000001000ebb6e in CGAL::import_from_polyhedron_subset<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Combinatorial_map<3u, CGAL::internal_IOP::Item_with_points_and_volume_info<CGAL::Epeck, CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> > >, std::__1::allocator<int>, CGAL::Combinatorial_map_storage_1<3u, CGAL::internal_IOP::Item_with_points_and_volume_info<CGAL::Epeck, CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> > >, std::__1::allocator<int> > >, std::__1::__list_iterator<CGAL::internal::In_place_list_const_iterator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Epeck, CGAL::I_Polyhedron_derived_items_3<SFCGAL::detail::Items_with_mark_on_hedge>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Epeck> > > >, std::__1::allocator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Epeck, CGAL::I_Polyhedron_derived_items_3<SFCGAL::detail::Items_with_mark_on_hedge>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Epeck> > > > > >, void*>, CGAL::internal_IOP::Non_intersection_halfedge<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> > >, std::__1::map<CGAL::internal::In_place_list_const_iterator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<SFCGAL::detail::Halfedge_with_mark<CGAL::HalfedgeDS_list_types<CGAL::Epeck, CGAL::I_Polyhedron_derived_items_3<SFCGAL::detail::Items_with_mark_on_hedge>, std::__1::allocator<int> > > > >, std::__1::allocator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<SFCGAL::detail::Halfedge_with_mark<CGAL::HalfedgeDS_list_types<CGAL::Epeck, CGAL::I_Polyhedron_derived_items_3<SFCGAL::detail::Items_with_mark_on_hedge>, std::__1::allocator<int> > > > > > >, CGAL::internal::CC_iterator<CGAL::Compact_container<CGAL::Dart<3u, CGAL::Combinatorial_map_storage_1<3u, CGAL::internal_IOP::Item_with_points_and_volume_info<CGAL::Epeck, CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> > >, std::__1::allocator<int> > >, std::__1::allocator<CGAL::Dart<3u, CGAL::Combinatorial_map_storage_1<3u, CGAL::internal_IOP::Item_with_points_and_volume_info<CGAL::Epeck, CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> > >, std::__1::allocator<int> > > >, CGAL::Default, CGAL::Default>, false>, CGAL::internal_IOP::Compare_address<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> > >, std::__1::allocator<std::__1::pair<CGAL::internal::In_place_list_const_iterator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<SFCGAL::detail::Halfedge_with_mark<CGAL::HalfedgeDS_list_types<CGAL::Epeck, CGAL::I_Polyhedron_derived_items_3<SFCGAL::detail::Items_with_mark_on_hedge>, std::__1::allocator<int> > > > >, std::__1::allocator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<SFCGAL::detail::Halfedge_with_mark<CGAL::HalfedgeDS_list_types<CGAL::Epeck, CGAL::I_Polyhedron_derived_items_3<SFCGAL::detail::Items_with_mark_on_hedge>, std::__1::allocator<int> > > > > > > const, CGAL::internal::CC_iterator<CGAL::Compact_container<CGAL::Dart<3u, CGAL::Combinatorial_map_storage_1<3u, CGAL::internal_IOP::Item_with_points_and_volume_info<CGAL::Epeck, CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> > >, std::__1::allocator<int> > >, std::__1::allocator<CGAL::Dart<3u, CGAL::Combinatorial_map_storage_1<3u, CGAL::internal_IOP::Item_with_points_and_volume_info<CGAL::Epeck, CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> > >, std::__1::allocator<int> > > >, CGAL::Default, CGAL::Default>, false> > > > > ()
(gdb) bt
#0  0x00000001000ebb6e in CGAL::import_from_polyhedron_subset<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Combinatorial_map<3u, CGAL::internal_IOP::Item_with_points_and_volume_info<CGAL::Epeck, CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> > >, std::__1::allocator<int>, CGAL::Combinatorial_map_storage_1<3u, CGAL::internal_IOP::Item_with_points_and_volume_info<CGAL::Epeck, CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> > >, std::__1::allocator<int> > >, std::__1::__list_iterator<CGAL::internal::In_place_list_const_iterator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Epeck, CGAL::I_Polyhedron_derived_items_3<SFCGAL::detail::Items_with_mark_on_hedge>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Epeck> > > >, std::__1::allocator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Epeck, CGAL::I_Polyhedron_derived_items_3<SFCGAL::detail::Items_with_mark_on_hedge>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Epeck> > > > > >, void*>, CGAL::internal_IOP::Non_intersection_halfedge<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> > >, std::__1::map<CGAL::internal::In_place_list_const_iterator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<SFCGAL::detail::Halfedge_with_mark<CGAL::HalfedgeDS_list_types<CGAL::Epeck, CGAL::I_Polyhedron_derived_items_3<SFCGAL::detail::Items_with_mark_on_hedge>, std::__1::allocator<int> > > > >, std::__1::allocator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<SFCGAL::detail::Halfedge_with_mark<CGAL::HalfedgeDS_list_types<CGAL::Epeck, CGAL::I_Polyhedron_derived_items_3<SFCGAL::detail::Items_with_mark_on_hedge>, std::__1::allocator<int> > > > > > >, CGAL::internal::CC_iterator<CGAL::Compact_container<CGAL::Dart<3u, CGAL::Combinatorial_map_storage_1<3u, CGAL::internal_IOP::Item_with_points_and_volume_info<CGAL::Epeck, CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> > >, std::__1::allocator<int> > >, std::__1::allocator<CGAL::Dart<3u, CGAL::Combinatorial_map_storage_1<3u, CGAL::internal_IOP::Item_with_points_and_volume_info<CGAL::Epeck, CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> > >, std::__1::allocator<int> > > >, CGAL::Default, CGAL::Default>, false>, CGAL::internal_IOP::Compare_address<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> > >, std::__1::allocator<std::__1::pair<CGAL::internal::In_place_list_const_iterator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<SFCGAL::detail::Halfedge_with_mark<CGAL::HalfedgeDS_list_types<CGAL::Epeck, CGAL::I_Polyhedron_derived_items_3<SFCGAL::detail::Items_with_mark_on_hedge>, std::__1::allocator<int> > > > >, std::__1::allocator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<SFCGAL::detail::Halfedge_with_mark<CGAL::HalfedgeDS_list_types<CGAL::Epeck, CGAL::I_Polyhedron_derived_items_3<SFCGAL::detail::Items_with_mark_on_hedge>, std::__1::allocator<int> > > > > > > const, CGAL::internal::CC_iterator<CGAL::Compact_container<CGAL::Dart<3u, CGAL::Combinatorial_map_storage_1<3u, CGAL::internal_IOP::Item_with_points_and_volume_info<CGAL::Epeck, CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> > >, std::__1::allocator<int> > >, std::__1::allocator<CGAL::Dart<3u, CGAL::Combinatorial_map_storage_1<3u, CGAL::internal_IOP::Item_with_points_and_volume_info<CGAL::Epeck, CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> > >, std::__1::allocator<int> > > >, CGAL::Default, CGAL::Default>, false> > > > > ()
#1  0x00000001000e5585 in CGAL::Node_visitor_refine_polyhedra<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Default, CGAL::Default, CGAL::Default, CGAL::Default>::finalize<CGAL::internal_IOP::Triangle_segment_intersection_points<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Epeck, CGAL::internal_IOP::Predicates_on_constructions, true> > ()
#2  0x00000001000dc97e in CGAL::Polyhedron_corefinement<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> >, CGAL::Epeck, CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> > >::operator()<CGAL::Emptyset_iterator, std::__1::back_insert_iterator<std::__1::vector<std::__1::pair<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> >*, int>, std::__1::allocator<std::__1::pair<CGAL::Polyhedron_3<CGAL::Epeck, SFCGAL::detail::Items_with_mark_on_hedge, CGAL::HalfedgeDS_default, std::__1::allocator<int> >*, int> > > > > ()
#3  0x0000000100264a06 in SFCGAL::algorithm::_intersection_solid_solid ()
#4  0x00000001002446d3 in CGAL::Box_intersection_d::modified_two_way_scan<std::__1::__wrap_iter<CGAL::Box_intersection_d::Box_with_handle_d<double, 3, SFCGAL::detail::PrimitiveHandle<3>*, CGAL::Box_intersection_d::ID_FROM_HANDLE>*>, std::__1::__wrap_iter<CGAL::Box_intersection_d::Box_with_handle_d<double, 3, SFCGAL::detail::PrimitiveHandle<3>*, CGAL::Box_intersection_d::ID_FROM_HANDLE>*>, SFCGAL::algorithm::intersection_cb<3>, CGAL::Box_intersection_d::Predicate_traits_d<CGAL::Box_intersection_d::Box_traits_d<CGAL::Box_intersection_d::Box_with_handle_d<double, 3, SFCGAL::detail::PrimitiveHandle<3>*, CGAL::Box_intersection_d::ID_FROM_HANDLE> >, true> > ()
#5  0x0000000100243bc1 in CGAL::Box_intersection_d::segment_tree<std::__1::__wrap_iter<CGAL::Box_intersection_d::Box_with_handle_d<double, 3, SFCGAL::detail::PrimitiveHandle<3>*, CGAL::Box_intersection_d::ID_FROM_HANDLE>*>, std::__1::__wrap_iter<CGAL::Box_intersection_d::Box_with_handle_d<double, 3, SFCGAL::detail::PrimitiveHandle<3>*, CGAL::Box_intersection_d::ID_FROM_HANDLE>*>, SFCGAL::algorithm::intersection_cb<3>, double, CGAL::Box_intersection_d::Predicate_traits_d<CGAL::Box_intersection_d::Box_traits_d<CGAL::Box_intersection_d::Box_with_handle_d<double, 3, SFCGAL::detail::PrimitiveHandle<3>*, CGAL::Box_intersection_d::ID_FROM_HANDLE> >, true> > ()
#6  0x000000010024341a in SFCGAL::algorithm::intersection<3> ()
#7  0x0000000100240253 in SFCGAL::algorithm::intersection3D ()
#8  0x0000000100240d7c in SFCGAL::algorithm::intersection3D ()
#9  0x000000010001a7fb in main ()
(gdb)
```

**Comment by kashif** [comment]
works fine with cgal 4.6, so closing this now.

**Comment by mhugo** [comment]
I don't have access to an OSX box. Is this still segfaulting ?

**Comment by kashif** [comment]
let me check @mhugo

**Comment by kashif** [comment]
doesnt crash closing
